export const UPDATE_SCAFFOLD_PROMPT_FALLBACK = `# Prompt: Update Repository Documentation and Agent Playbooks

## Purpose
You are an AI assistant responsible for refreshing the documentation (\`docs/\`) and agent playbooks (\`agents/\`) generated by the ai-context scaffolding tool. Your goal is to bring every guide up to date with the latest repository state, fill in placeholder sections, and maintain cross-references between docs and agent instructions.

## Context Gathering Checklist
1. Run \`git status -sb\` to understand pending changes.
2. Review the latest merged commits or PRs related to documentation, architecture, workflow, or testing.
3. Inspect \`package.json\`, CI configuration, and any release or roadmap notes stored in the repository.
4. Check \`docs/README.md\` for the current document map and confirm each guide listed still exists.
5. Identify unresolved \`TODO\` prompts or sections flagged for human follow-up.

## Update Procedure
1. **Select a Guide**
   - Navigate to \`docs/<guide>.md\`.
   - Read the YAML front matter (\`ai_update_goal\`, \`required_inputs\`, \`success_criteria\`) and ensure you collect the listed inputs before editing.

2. **Edit the Guide**
   - Keep the YAML front matter intact but update any fields that have changed.
   - Replace every \`TODO\` prompt with accurate, current information.
   - Refresh examples, tables, and summaries so they reflect the latest repository state.

3. **Cross-Link Updates**
   - Verify that links between docs remain valid.
   - If you add new guides or sections, update \`docs/README.md\` and the document map table.

4. **Agent Playbook Alignment**
 - For each change in \`docs/\`, adjust the related \`agents/*.json\` playbooks.
  - Ensure the "Documentation Touchpoints" list references the relevant guides and accurately describes why they matter.
  - Update collaboration checklists and evidence sections to reflect the latest workflows.

5. **Test Plan Refresh**
   - Update \`test-plan.json\` with the latest frontend and backend scenarios that reflect documentation changes.
   - Keep scenario IDs stable while replacing \`TODO\` placeholders with concrete Given/When/Then expectations and related files.
   - Align recommended sources and checklists with any new guidance added across docs and agents.

6. **Evidence & Traceability**
   - Note key sources (commit hashes, issues, ADRs) in the "Evidence to Capture" or "AI Update Checklist" summary lines.
   - If anything is ambiguous or requires human follow-up, leave a concise note clearly labelled for maintainers.

## Acceptance Criteria
- Every guide’s \`success_criteria\` field is satisfied.
- No unresolved \`TODO\` prompts remain unless they require explicit human input; in such cases, add a comment explaining the dependency.
- Agent playbooks list accurate responsibilities, best practices, and pointer links to the refreshed docs.
- Changes are self-contained, well-formatted Markdown, and reference any new external resources introduced.

## Deliverables
- Updated Markdown files committed to the repository.
- A short changelog or PR description summarizing:
  - Guides touched
  - Key decisions or facts added
  - Evidence links and any pending follow-ups
`;

export const UPDATE_PLAN_PROMPT_FALLBACK = `# Prompt: Update Collaboration Plans

## Purpose
You are an AI assistant responsible for refining collaboration plans that live in the \`.context/plans/\` directory. Each plan orchestrates work across documentation guides (\`docs/\`) and agent playbooks (\`agents/\`). Your goal is to replace placeholders with actionable guidance that keeps the plan aligned with the referenced docs, agents, and repository context.

## Preparation Checklist
1. Review the plan’s YAML front matter to understand the stated \`ai_update_goal\`, \`required_inputs\`, and \`success_criteria\`.
2. Inspect the provided documentation excerpts (from \`docs/\`) and agent playbooks to ensure the plan reflects their current guidance.
3. Confirm that the “Agent Lineup” and “Documentation Touchpoints” tables link to real files and describe why each resource matters.
4. Note any TODO prompts or missing evidence sections that must be resolved.

## Update Procedure
1. **Task Snapshot**
   - Summarize the primary goal and success signal in concrete terms.
   - List authoritative references (docs, issues, specs) that contributors should consult.

2. **Agent Alignment**
   - For each agent in the lineup, describe why they are involved and call out the first responsibility they should focus on.
   - Ensure playbook links and responsibility summaries match the referenced agent files.

3. **Documentation Touchpoints**
   - Map each plan stage to the docs excerpts provided, highlighting which sections need to be updated during execution.
   - Keep the table sorted and ensure each entry explains the guide’s focus or primary inputs.

4. **Working Phases**
   - Break the work into sequential phases that each include a numbered list of steps, accountable owners, deliverables, and evidence expectations.
   - Close every phase with an explicit Git commit checkpoint (for example, \`git commit -m "chore(plan): complete phase 1"\`) so progress is recorded in version control.
   - Reference documentation and agent resources that the team should consult while executing each phase.

5. **Evidence & Follow-up**
   - Specify the artefacts that must be captured (PR links, test runs, change logs) before the plan is considered complete.
   - Record any follow-up actions or decisions that require human confirmation.

## Acceptance Criteria
- Every TODO prompt inside the plan is resolved or accompanied by a clear escalation note.
- Tables reference existing files and stay in sync with the docs/agent indices.
- Phases provide actionable guidance, include numbered steps, and end with an explicit Git commit checkpoint.
- The plan remains fully self-contained and ready for contributors to execute.

## Deliverables
- Updated plan Markdown returned verbatim.
- No additional commentary outside the Markdown output.
`;
